[build-system]
requires = ["setuptools>=42", "setuptools_scm[toml]>=6.3"]
build-backend = "setuptools.build_meta"

[project]
name = "dserver-minimal"
description = "Meta-package for installing a minimal working dserver consisting of dtool-lookup-server, dserver-search-plugin-mongo, and dserver-retrieve-plugin-mongo"
license = {file = "LICENSE"}
authors = [
    {name = "Tjelvar Olsson", email = "tjelvar.olsson@gmail.com"},
    {name = "Johannes L. Hörmann", email = "johannes.laurin@gmail.com"}
]
dependencies = [
      "dtool-lookup-server @ git+https://github.com/jic-dtool/dtool-lookup-server.git#master",
      "dserver-search-plugin-mongo @ git+https://github.com/livMatS/dserver-search-plugin-mongo.git#main",
      "dserver-retrieve-plugin-mongo @ git+https://github.com/livMatS/dserver-retrieve-plugin-mongo.git#main",
    ]
dynamic = ["version"]

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx_rtd_theme",
    "sphinxcontrib-spelling",
    "myst-parser==2.0.0"
]

[project.urls]
Documentation = "https://dserver-minimal.readthedocs.io"
Repository = "https://github.com/livMatS/dserver-minimal"

[tool.setuptools]
packages = ["dserver_minimal"]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
write_to = "dserver_minimal/version.py"

