name: containers
# Build-test the dserver_devel image on push/PR (no push to a registry).

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v5

    - name: docker meta
      id: docker_meta
      uses: docker/metadata-action@v5.8.0
      with:
        images: local/dserver-devel
        tags: |
          type=raw,value=sha-${{ github.sha }}

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: build
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./docker/dserver_devel/Dockerfile
        platforms: linux/amd64
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        outputs: type=docker, dest=/tmp/image.tar
        cache-from: type=gha
        cache-to: type=gha,mode=max
